global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['broker:9101']

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:2181']

  - job_name: 'airflow'
    static_configs:
      - targets: ['webserver:8080']

  - job_name: 'spark'
    static_configs:
      - targets: ['spark-master:9090']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
